version: '1.0'
# This is a sample docker-compose file for running Kafka and Zookeeper with Kafdrop
# Run all Services
services:
  # Run service
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  # Run service
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  # Run service
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    #container_name: kafdrop
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  # producer:
  #   image: ruimiguelsoares/producer-json-serializer:1.0.0
  #   platform: linux/arm64
  #   networks:
  #     - broker-kafka
  #   depends_on:
  #     - kafka
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     KAFKA_HOST: kafka:29092
  #     PORT: 8001
  # consumer:
  #   image: ruimiguelsoares/consumer-json-serializer:1.0.0
  #   platform: linux/arm64
  #   networks:
  #     - broker-kafka
  #   depends_on:
  #     - kafka
  #     - producer
  #   environment:
  #     KAFKA_HOST: kafka:29092 
# Network for the services
networks:
  broker-kafka:
    driver: bridge